apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: solar
  labels:
    app: backend
spec:
  clusterIP: None
  ports:
    - port: 8000
      name: http
  selector:
    app: backend
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: backend
  namespace: solar
spec:
  serviceName: backend
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          # Phony container registry for demo
          image: solaracr.azurecr.io/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: CORS_ALLOW_ALL_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: CORS_ALLOW_ALL_ORIGINS
            - name: DJANGO_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DJANGO_DEBUG
            # - name: REDIS_URL
            #   valueFrom:
            #     configMapKeyRef:
            #       name: backend-config
            #       key: REDIS_URL
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DJANGO_SECRET_KEY
            - name: NREL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: NREL_API_KEY

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
