services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - 3000:3000
    env_file:
      - path: ./frontend/.env
        required: true
    environment:
      - API_URL=http://backend:8000

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - 8000:8000
    env_file:
      - path: ./backend/.env
        required: true

  # For future caching of calls to our
  # pitch endpoint.
  #
  # redis:
  #   image: redis:latest
  #   restart: always
  #   ports:
  #     - 6379:6379
