apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ .Values.namespace }}
  labels: {{- include "solar.labels" . | nindent 4 }}
data:
  DJANGO_DEBUG: {{ .Values.backend.env.DJANGO_DEBUG | quote }}
  CORS_ALLOW_ALL_ORIGINS: {{ .Values.backend.env.CORS_ALLOW_ALL_ORIGINS | quote }}
