apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
  labels:
    app: backend
spec:
  clusterIP: None
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
  selector:
    app: backend
