apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DJANGO_SECRET_KEY: {{ .Values.backend.secret.DJANGO_SECRET_KEY | quote }}
  NREL_API_KEY: {{ .Values.backend.secret.NREL_API_KEY | quote }}
