apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
spec:
  serviceName: backend
  replicas: {{ .Values.replicaCount.backend }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}/backend:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
              name: http
          env:
            - name: DJANGO_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DJANGO_DEBUG
            - name: CORS_ALLOW_ALL_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: CORS_ALLOW_ALL_ORIGINS
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DJANGO_SECRET_KEY
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
