apiVersion: v1
kind: Secret
metadata:
  name: frontend-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  PUBLIC_GOOGLE_MAPS_API_KEY: {{ .Values.frontend.secret.PUBLIC_GOOGLE_MAPS_API_KEY | quote }}
