apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:chevcast/solar-technical-assessment.git
    targetRevision: main
    path: infra/k8s/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: solar
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
