apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-issuers
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:chevcast/solar-technical-assessment.git
    targetRevision: main
    path: infra/k8s/cluster-issuers
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
